include: package:flutter_lints/flutter.yaml

linter:
  rules:

dart_code_metrics:
  extends:
    - recommended
  rules:
    - prefer-trailing-comma: false
    - prefer-single-widget-per-file: false
    - unnecessary-trailing-comma: false
    - avoid-shadowing: false
    - prefer-match-file-name: false
    - no-empty-block: false
    - avoid-unsafe-collection-methods: false
    - avoid-redundant-else: false
    - avoid-missing-controller: false
    - prefer-correct-callback-field-name: false