name: code_with_andrea_flutter
description: Flutter clone of the home page at codewithandrea.com
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  vector_graphics: 1.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  vector_graphics_compiler: 1.1.11
  build_runner: 2.4.11
  flutter_gen_runner: 5.6.0

flutter:
  uses-material-design: false

  assets:
    - assets/
    - assets/fonts/
    - path: assets/svg/
      transformers:
        - package: vector_graphics_compiler